name: PokiePaws CI

on:
  push:
    branches: [ "main", "feature/**" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      # 1. Kontrola jakości
      - name: Run ktlint
        run: ./gradlew ktlintCheck

      - name: Run detekt
        run: ./gradlew detekt

      # 2. Testy i Budowanie
      - name: Run unit tests
        run: ./gradlew testDebugUnitTest

      - name: Build debug APK
        run: ./gradlew assembleDebug

      - name: Upload Lint Reports
        if: always() # Raporty zostaną wysłane nawet jeśli build się wywali
        uses: actions/upload-artifact@v4
        with:
          name: pokiepaws-quality-reports
          path: |
            app/build/reports/ktlint/
            app/build/reports/detekt/
          retention-days: 7

      # 4. Wrzucanie gotowej aplikacji APK
      - name: Upload Debug APK
        if: success() # APK wysyłamy tylko, gdy wszystko przeszło pomyślnie
        uses: actions/upload-artifact@v4
        with:
          name: pokiepaws-app-debug
          path: app/build/outputs/apk/debug/*.apk
          retention-days: 14